SECRET_KEY = ""
#服务器密钥
without_redis = false
#是否使用redis缓存，true为使用json文件缓存，false为使用redis缓存
[redis]
host = "127.0.0.1"
port = 6379
db = 0
#redis配置 password = ""

[Data_limit_default]
pc = 20
browser = 20
phone = 20
#默认单用户数据限制条数

[steam]
enable = true
steam_id = 76561199077836301
steam_key = ""
#steam配置 steam_key: https://steamcommunity.com/dev/apikey

[bgm]
Auth = ""
#bgm配置 Auth: https://bangumi.github.io/api/

[openai]
base_url = "https://api.uniapi.io/v1"
api_key = "sk-xxx"
model = "deepseek-v3.2-exp"
#openai配置 api_key: https://platform.openai.com/account/api-keys

[recaptcha]
secret=""
#recaptcha v2 secret key https://www.google.com/recaptcha/admin/create

[notification]
enable = false
methods = "pushplus"

# PushPlus https://www.pushplus.plus/
[notification.pushplus]
token = "" 
